---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "main.yml"

- name: Define redis_package.
  set_fact:
    redis_package: "{{ __redis_package }}"
  when: redis_package is not defined
- name: Ensure Redis is installed.
  apt:
    deb: "https://s3.amazonaws.com/guru-packages/redis_4.0.0_amd64.deb"
- name: Ensure Redis is configured.
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    mode: 0644
  notify: restart redis

- name: /etc/default/redis-server conf file
  template:
    src: redis-server.j2
    dest: /etc/default/redis-server
    mode: 0644
  notify: restart redis

- name: Ensure redis service is configured.
  template:
    src: redis-server.service.j2
    dest: /lib/systemd/system/redis-server.service
    mode: 0644
  notify: restart redis
  register: redis_service_changed

- name: sudo systemctl daemon-reload
  command: sudo systemctl daemon-reload
  when: redis_service_changed.changed

- name: Ensure Redis is running and enabled on boot.
  service: "name={{ redis_daemon }} state=started enabled=yes"

- name: add a vm.overcommit_memory setting at the end of the sysctl.conf
  sysctl: name=vm.overcommit_memory value=1 state=present reload=yes

# WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis
- name: update init script
  template:
    src: rc.local.j2
    dest: /etc/rc.local
    owner: root
    group: root
    mode: 0755
    validate: '/usr/bin/env sh -n %s'
  notify: execute rc.local
  tags:
    - rc-local
    - rc-local-init