---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "main.yml"

- name: Define redis_package.
  set_fact:
    redis_package: "{{ __redis_package }}"
  when: redis_package is not defined
- name: Ensure Redis is installed.
  apt:
    deb: "https://s3.amazonaws.com/guru-packages/redis_4.0.0_amd64.deb"
- name: Ensure Redis is configured.
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    mode: 0644
  notify: restart redis

- name: create redis group
  group: name=redis state=present system=yes
- name: create redis user
  user: name=redis group=redis createhome=no shell=/bin/false system=yes state=present

- name: make sure that /var/lib/redis exists
  file: path=/var/lib/redis state=directory mode=0755 group=redis owner=redis

- name: make sure that /var/run/redis exists
  file: path=/var/run/redis state=directory mode=1755 group=redis owner=redis

- name: make sure that /var/log/redis exists
  file: path=/var/log/redis state=directory mode=0755 group=redis owner=redis

- name: make sure that /var/log/redis/redis-server.log exists
  file: path=/var/log/redis/redis-server.log state=touch mode=0755 group=redis owner=redis


- name: /etc/default/redis-server conf file
  template:
    src: redis-server.j2
    dest: /etc/default/redis-server
    mode: 0644
  notify: restart redis

- name: Ensure redis service is configured.
  template:
    src: redis-server.service.j2
    dest: /lib/systemd/system/redis-server.service
    mode: 0644
  notify: restart redis
  register: redis_service_changed

- name: sudo systemctl daemon-reload
  command: sudo systemctl daemon-reload
  when: redis_service_changed.changed

- name: Ensure Redis is running and enabled on boot.
  service: "name={{ redis_daemon }} state=started enabled=yes"

- name: add a vm.overcommit_memory setting at the end of the sysctl.conf
  sysctl: name=vm.overcommit_memory value=1 state=present reload=yes

# WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis
- name: update init script
  template:
    src: rc.local.j2
    dest: /etc/rc.local
    owner: root
    group: root
    mode: 0755
    validate: '/usr/bin/env sh -n %s'
  notify: execute rc.local
  tags:
    - rc-local
    - rc-local-init
- name: Import Docker CE repository gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Add Docker CE repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker CE
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: Enable Docker CE service on startup
  service:
    name: docker
    state: started
    enabled: yes

- name: "Deploy Redis exporter"
  docker_container:
    docker_api_version: auto
    name: "redis-exporter"
    image: "oliver006/redis_exporter"
    pull: true
    detach: "{{ detachFlag | default('true') }}"
    cleanup: "{{ cleanupFlag | default('false') }}"
    restart_policy: "{{ restartPolicy | default('always') }}"
    state: started
    command: "-redis.addr=172.17.0.1:6379"
    volumes: "{{ docker_node_volumes | default([]) }}"
    etc_hosts: "{{ containerHosts | default() }}"
    env: "{{ env | | default()}}"
    dns_search_domains: "{{ dns_search_domains | | default() }}"
    dns_servers: "{{ dns_servers | default() }}"
    published_ports:
      - "9121:9121"
