- name: Add pam_limits module to common session configs
  lineinfile: dest='/etc/pam.d/{{ item }}' line='session required pam_limits.so' insertbefore='# end of pam-auth-update config'
  with_items:
    - "common-session"
    - "common-session-noninteractive"

- name: install ulimits.conf
  become: yes
  become_user: root
  become_method: sudo
  template: >
    src=91-nofiles.conf.j2
    dest=/etc/security/limits.d/91-nofiles.conf
    owner=root
    group=root
    mode=0644
  tags: [ulimit]

- name: Set sysctl File Limits
  become: yes
  become_user: root
  become_method: sudo
  template: >
    src=50-fs.conf.j2
    dest=/etc/sysctl.d/50-fs.conf
    owner=root
    group=root
    mode=0644
  tags: [ulimit]

- name: change comment /etc/security/limits.conf
  lineinfile:
    dest=/etc/security/limits.conf
    regexp="^# Ansible changes."
    line="# Ansible changes."
  tags: [ulimit]

- name: change soft /etc/security/limits.conf
  lineinfile:
    dest=/etc/security/limits.conf
    regexp="^\* soft nofile"
    line="* soft nofile {{ ulimit_num | default('300000') }}"
  tags: [ulimit]

- name: change hard /etc/security/limits.conf
  lineinfile:
    dest=/etc/security/limits.conf
    regexp="^\* hard nofile"
    line="* hard nofile {{ ulimit_num | default('300000') }}"
  tags: [ulimit]
  register: limits_changed

- name: Reload systemctl
  shell: sysctl -p
  when: limits_changed.changed